service: serverless-rest-fullstack-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    TABLE_NAME: ${self:service}-users-${self:provider.stage}
    SERVERLESS_DIR: backend
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${opt:region, 'us-east-1'}:*:table/${self:provider.environment.TABLE_NAME}

plugins:
  - serverless-offline

functions:
  createUser:
    handler: src/handlers/createUser.create
    events:
      - http:
          path: users
          method: post
          cors:
            origin:
              - http://localhost:5173
              - https://serverless-api-gateway.vercel.app
            headers:
              - Content-Type
            allowCredentials: false

  listUsers:
    handler: src/handlers/listUsers.readAll
    events:
      - http:
          path: users
          method: get
          cors:
            origin:
              - http://localhost:5173
              - https://serverless-api-gateway.vercel.app
            headers:
              - Content-Type
            allowCredentials: false

  getUser:
    handler: src/handlers/getUser.read
    events:
      - http:
          path: users/{userId}
          method: get
          cors:
            origin:
              - http://localhost:5173
              - https://serverless-api-gateway.vercel.app
            headers:
              - Content-Type
            allowCredentials: false

  updateUser:
    handler: src/handlers/updateUser.update
    events:
      - http:
          path: users/{userId}
          method: patch
          cors:
            origin:
              - http://localhost:5173
              - https://serverless-api-gateway.vercel.app
            headers:
              - Content-Type
            allowCredentials: false

  deleteUser:
    handler: src/handlers/deleteUser.delete
    events:
      - http:
          path: users/{userId}
          method: delete
          cors:
            origin:
              - http://localhost:5173
              - https://serverless-api-gateway.vercel.app
            headers:
              - Content-Type
            allowCredentials: false

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
